name: ci
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'   # Only trigger on tag push


jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Less is More.
          files: |
            ./result/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}